cmake_minimum_required(VERSION 3.25)

project(sender_receiver LANGUAGES CXX CUDA)

if(PROJECT_IS_TOP_LEVEL)
    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)
    set(CMAKE_CUDA_STANDARD 20)
    set(CMAKE_CUDA_STANDARD_REQUIRED ON)
    set(CMAKE_CUDA_EXTENSIONS OFF)
endif()

file(GLOB_RECURSE SENDER_RECEIVER_SOURCES CONFIGURE_DEPENDS
     "${CMAKE_CURRENT_SOURCE_DIR}/*.c"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.cc"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.cxx"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.cu")
file(GLOB_RECURSE SENDER_RECEIVER_HEADERS CONFIGURE_DEPENDS
     "${CMAKE_CURRENT_SOURCE_DIR}/*.h"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.hh"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.hpp"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.hxx"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.cuh"
     "${CMAKE_CURRENT_SOURCE_DIR}/*.inl")

add_executable(sender_receiver ${SENDER_RECEIVER_SOURCES} ${SENDER_RECEIVER_HEADERS})
set_target_properties(sender_receiver PROPERTIES CUDA_ARCHITECTURES native)
source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" FILES ${SENDER_RECEIVER_SOURCES} ${SENDER_RECEIVER_HEADERS})
